services:
  - type: web
    name: bot-paris-telegram
    env: python
    pythonVersion: 3.10.13  # ✅ Plus sûr pour snscrape, 3.11.9 peut encore poser problème
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
